### ISSUE TITLE
Geom_bar looks stripped

### ISSUE THREAD

**Issue by ACalleros** [r-lib/ragg#96]
I am trying to do a bar plot using ragg as my driver but it looks stripped compared with cairo. I tried changing antialiasing parameters but it still looks the same. 

![49687db4-090d-4650-bfe3-307edf8eb31e](https://user-images.githubusercontent.com/36737154/141433805-c8e171c0-0272-42e0-8f5a-3b744d0537da.png)
![c3b6aca8-f057-4f14-9d75-6ab74fb35be2](https://user-images.githubusercontent.com/36737154/141433859-6504b467-e1c4-4ea4-931b-cd0a05f1a1db.png)
)

**Comment by thomasp85** [comment]
well, there are no antialiasing parameters in ragg to change... you are right that it is probably related to it. The reason is that Cairo has elected to never antialias fill. This helps in this particular situation but makes non-rectangular shapes look horrible... Maybe I should add a switch to allow rectangles to forego antialiasing🤷‍♂️

If you need an immediate fix you can add a thin border of the same colour to the bars, but that is of course a crutch
